wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.15
    start_time: 1757950915
    t:
      1:
      - 1
      - 55
      3:
      - 16
      4: 3.10.15
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 256
dataset:
  desc: null
  value: /workspace/rosbag_recordings/hdf5_datasets/mini_pupper_demos_20250914_233847.hdf5
hidden_dims:
  desc: null
  value:
  - 512
  - 256
  - 128
lr:
  desc: null
  value: 0.0003
model:
  desc: null
  value: MLP
